FROM denoland/deno:alpine-2.0.6

# Create non-root user
RUN getent group deno >/dev/null 2>&1 || addgroup -S deno \
  && id -u deno >/dev/null 2>&1 || adduser -S deno -G deno

WORKDIR /app/functions

COPY --chown=deno:deno functions /app/functions

USER deno
